### ISSUE TITLE
walkGlobKinds(".") excludes "." ; needs to be documented: consistent with `python glob` but inconsistent with unix `find .`

### ISSUE THREAD

**Issue by timotheecour** [citycide/glob#13]

**Comment by citycide** [comment]
Looks like `find`/unix glob expands the lone `.` into `**/*`? That's consistent with the `expandDirs` option I guess, so which route do we want to go - update docs or match unix?

**Comment by timotheecour** [comment]
probably best is to add a flag: `includeTopLevelDir` (false by default)

**Comment by citycide** [comment]
Hmm actually I just tested this out on Windows and in WSL bash &mdash; glob does the same thing unix's `find` does and expands `"."` and `".."` into their directories when `expandDirs == true` (default).

**Comment by timotheecour** [comment]
honestly it doesn't matter which default is used (clearly different tools use different convention here) so long there's an option (eg `includeTopLevelDir`)

**Comment by citycide** [comment]
@timotheecour then I'm going to close this one, because it's just a directory same as any other so I don't see why it should be treated differently

**Comment by citycide** [comment]
If `foo` is a directory you'll have to use `includeDirs = true` as documented to include it in the results.

**Comment by timotheecour** [comment]
actually both python `glob.glob` and unix `find` return top-level dir:
find bar
bar
bar/bar2
bar/bar2/bar3
bar/f1.txt

glob.glob('bar/**', recursive=True)
Out[17]: ['bar/', 'bar/bar2', 'bar/bar2/bar3', 'bar/f1.txt']
