### ISSUE TITLE
Optimize file system walking

### ISSUE THREAD

**Issue by citycide** [citycide/glob#2]
Right now we use [`walkDirRec`](https://nim-lang.org/docs/os.html#walkDirRec.i,string) which traverses recursively into directories automatically. This means `glob` potentially walks over a lot of files that the given pattern might completely ignore. Instead it should probably use [`walkDir`](https://nim-lang.org/docs/os.html#walkDir.i,string) so that we can decide whether to recurse into the directories as we come across them.

**Comment by data-man** [comment]
Related RFC https://github.com/nim-lang/Nim/issues/7077 :smile:

**Comment by citycide** [comment]
@data-man thanks although I ended up basically modifying `walkDirRec` and adding logic as needed. Any chance you could check out the PR? I want to run a comparison test on a fairly large directory structure before merging, but it should be good otherwise.

_(this reminds me I still need to set up CI)_
