### ISSUE TITLE
if pattern is absolute, don't transform it to relative by default (cf unix find)

### ISSUE THREAD

**Issue by timotheecour** [citycide/glob#23]
cd /tmp/foo

```nim
import glob

proc test()=
  let src_D="/tmp/foo/tests/nim/t48_glob/**/*" #NOTE: the pattern is absolute
  for a in walkGlobKinds(src_D): echo a

test()
```
prints:
```
(path: "tests/nim/t48_glob/test.nim", kind: pcFile)
(path: "tests/nim/t48_glob/a/b3.txt", kind: pcFile)
```

should print:
```
(path: "/tmp/foo/tests/nim/t48_glob/test.nim", kind: pcFile)
(path: "/tmp/foo/tests/nim/t48_glob/a/b3.txt", kind: pcFile)
```

**EDIT**
so basically what I'm suggesting is to either change meaning of `GlobOption.Absolute` to have its default match behavior of unix `find`:

Absolute = true:
all paths converted to absolute

Absolute = false and root = "" (the default)
if pattern in relative,  stay relative
if pattern in absolute,  stay absolute

Absolute = false and root != ""
all paths converted to be relative to root (using `relativePath` from https://github.com/nim-lang/Nim/pull/8166#issuecomment-405685942 once ready; until then using whatever logic you have, which IIRC is currently different, as you don't allow ".." IIRC)

/cc @citycide what do you think?

**Comment by citycide** [comment]
Isn't that confusing? Shouldn't providing `GlobOption.Absolute` just _always_ determine how the paths are returned? I'd be really surprised if I passed `Absolute` but got back relative paths.

**Comment by timotheecour** [comment]
the problem is current setup doesn't allow you to preserve absolute-ness of input pattern: if `Absolute` were a tri-state (off/on/auto) that would solve that issue. But since it's a 2-state bit, the way I suggest allows user to preserve absolute-ness.

The way I suggest (preserving absolute-ness) not only makes more sense but is what is standard pretty much everywhere:
* same as unix find
* same as python glob
* same as nim `walkPattern`
* same as D's dirEntries
etc...
