### ISSUE TITLE
[RFC] regarding committing docs and auto-updating documentation website

### ISSUE THREAD

**Issue by timotheecour** [citycide/glob#25]
I'm currently seeing docs/glob/regexer.html + other files

* committing docs doesn't seem good since these are autogenerated
(see https://blog.kentcdodds.com/why-i-don-t-commit-generated-files-to-master-a4d76382564 for eg)

* https://citycide.github.io/glob/ should reflect latest docs (or at least have an option to show latest docs, eg via url, eg: 
- https://citycide.github.io/glob/version/master/
- https://citycide.github.io/glob/version/0.8.0/

* ideally docs there would be updated after each PR merged, automatically

## implementation
* I'm curious whether .travis.yml or .appveyor.yml be used for that purpose? (since these are run after each PR is updated I'm curious whether that use case is supported or how to do that simply)

* or maybe git hooks: https://www.digitalocean.com/community/tutorials/how-to-use-git-hooks-to-automate-development-and-deployment-tasks

* in github: webhooks https://developer.github.com/webhooks/creating/

**Comment by citycide** [comment]
I've never generated artifacts like this using CI but it's a good idea (or hooks, if that's better). Would like to find a good way to do this.

**Comment by citycide** [comment]
I started this but we're blocked by https://github.com/nim-lang/Nim/issues/9155.

**Comment by citycide** [comment]
@timotheecour done! :tada: 

Well, not done, but it works heh. There are definitely improvements to be made. Basically how it works is: untagged git commits do nothing extra on Travis and the tests are run as usual.

A tagged commit however (which should be a new version) will [trigger](https://github.com/citycide/glob/blob/31111ddfcf07889f2ee44308a765e29cab3ee142/.travis.yml#L38-L42) a custom Travis deploy script found in [.travis_deploy_docs](https://github.com/citycide/glob/blob/31111ddfcf07889f2ee44308a765e29cab3ee142/.travis_deploy_docs). It overwrites the `master` directory on the `gh-pages` branch and also creates a new directory named with the tag on the commit.

Now I want to put in an index file that catalogs these versions and I think we'll be in good shape.

**Comment by timotheecour** [comment]
> Now I want to put in an index file that catalogs these versions and I think we'll be in good shape.

after that I think it'd be worth adding a link to that technique to nim github repo in best practices (permanent, easy to search) or at least a forum entry

**Comment by citycide** [comment]
Aight, now it's pretty great. Check it out: https://citycide.github.io/glob/

* added a landing page with quick links to the GitHub repo and latest docs
* added release history with links to docs & release notes for that version
* added some redirecting index files so `{url}/latest` is equiv. to `{url}/latest/glob.html`

**Comment by timotheecour** [comment]
perfect!
