### ISSUE TITLE
FileSystemCaseSensitive should now be used now that https://github.com/nim-lang/Nim/pull/8411 was merged

### ISSUE THREAD

**Issue by timotheecour** [citycide/glob#26]
my PR https://github.com/nim-lang/Nim/pull/8411 was merged, so FileSystemCaseSensitive should now be used instead of duplicating logic

**Comment by citycide** [comment]
Already being [used here](https://github.com/citycide/glob/blob/d2d4eee257d4940932625c262ddcf428f5c2bdb1/src/glob.nim#L291) but could be used [here too](https://github.com/citycide/glob/blob/d2d4eee257d4940932625c262ddcf428f5c2bdb1/src/glob.nim#L232).

**Comment by citycide** [comment]
Fixed in `glob` but be aware part of the fix needs to be in a Nim release too.

**Comment by timotheecour** [comment]
> be aware part of the fix needs to be in a Nim release too.

not sure what you mean; you mean the user won't benefit of this fix unless they use recent enough version of nim devel? if so, ya, that kinda stuff will be common...

**Comment by citycide** [comment]
Yes but eventually it will make it to stable. FYI I plan to be pretty aggressive with requiring those as Nim closes in on 1.0.
