### ISSUE TITLE
glob patterns like "*/z1.txt" don't work (ie when a glob happens before / it seems)

### ISSUE THREAD

**Issue by timotheecour** [citycide/glob#29]
/cc @citycide this bug seems serious:

on linux:

find `pwd`
/tmp/d03
/tmp/d03/A1
/tmp/d03/A1/z2.txt
/tmp/d03/A1/Z2.txt
/tmp/d03/a1
/tmp/d03/a1/z1.txt

```
echo toSeq(walkGlob("a1/z1.txt"))
@["a1/z1.txt"]
echo toSeq(walkGlob("*/z1.txt"))
@[] # BUG
echo toSeq(walkGlob("a?/z1.txt"))
@[]  # BUG
echo toSeq(walkGlob("a?/z?.txt"))
@[]  # BUG
```

**Comment by timotheecour** [comment]
@citycide can we reopen? still doesn't work properly:
in example above, do:
cd ..

ls */*/z1.txt
d03/a1/z1.txt  d04/a1/z1.txt

```nim
import glob,sequtils
echo toSeq(walkGlob("*/*/z1.txt"))
@[]
```

**Comment by timotheecour** [comment]
@citycide friendly ping :) this bug really limits usability of this otherwise excellent tool ...

**Comment by citycide** [comment]
Yeah I'm working on it but it hasn't been as simple as I thought it would be. Still in progress.

**Comment by timotheecour** [comment]
@citycide can you adapt https://github.com/git/git/blob/master/wildmatch.c to Nim? that seems like exactly what we want

**Comment by citycide** [comment]
@timotheecour that doesn't support extended glob features like `{}` groups and patterns. It's also not the problem area: matching works fine as-is, it's the file system traversal that is difficult because we need to partially match directories along the way.

**Comment by data-man** [comment]
> doesn't support extended glob features like {} groups and patterns

Exactly!
So I prefer [filename_match](https://github.com/fltk/test-only/blob/branch-1.4/src/filename_match.cxx#L44) from FLTK.
