### ISSUE TITLE
Error: cannot evaluate at compile time: pattern

### ISSUE THREAD

**Issue by timotheecour** [citycide/glob#34]
```nim
when defined(case1):
  # Error: cannot evaluate at compile time: pattern
  import pkg/glob
  let pattern = "foo"
  let a = re(pattern)

when defined(case2):
  # ok
  import std/nre
  let pattern = "foo"
  let a = re(pattern)
```

nre supports runtime regex, but not glob

**Comment by citycide** [comment]
This is actually not a glob issue it's the underlying `regex` package. Could you move this over there?

https://github.com/nitely/nim-regex/issues

**Comment by citycide** [comment]
Also it works if you declare `pattern` as a `const` rather than a `let`.

**Comment by nitely** [comment]
@timotheecour why would you prefer nre over nim-regex?

**Comment by citycide** [comment]
> just out of curiosity: do you know how much work (doesn't mean by "you" necessarily btw :) ) to use nre instead of nim-regex

Use it for what, `glob`? If so I think the API is different but the actual regex pattern syntax is probably the same.

> why would you prefer nre over nim-regex?

I'm also curious about those reasons

**Comment by timotheecour** [comment]
> why would you prefer nre over nim-regex?
> I'm also curious about those reasons

precisely the OP: allowing using regex at RT instead of CT; but it's all being sorted out ; it's possible with `toPattern` and soon via `re` too (see my PR https://github.com/nitely/nim-regex/pull/27)

**Comment by timotheecour** [comment]
it now works now that  nitely/nim-regex#27 was merged; just edited OP
