### ISSUE TITLE
github action CI broken

### ISSUE THREAD

**Issue by timotheecour** [citycide/glob#44]
* seems to be caused by https://github.com/dom96/choosenim/issues/122#issuecomment-576043187
* could this help https://github.com/nim-lang/Nim/wiki/BuildServices ?
(in case this https://github.com/jiro4989/setup-nim-action doesn't work, cf https://github.com/citycide/glob/commit/ad4e1eac1bb55799b57e9f4b6308d6306124cee0)

**Comment by citycide** [comment]
@timotheecour I've disabled macOS on github actions, but it's currently still tested on travis. We'll revisit in the future.
