### ISSUE TITLE
walkGlob returns paths with `/` instead of `\` on windows

### ISSUE THREAD

**Issue by timotheecour** [citycide/glob#46]
this test seems weird on windows:
```nim
      check seqsEqual(toSeq(walkGlob("temp")), @[
        p"temp/deep/dir/file.nim",
        p"temp/not_as/deep.jpg",
        p"temp/not_as/deep.nim",
        p"temp/shallow.nim"
      ])
```

shouldn't it return paths with `\` on windows (like os.walkDirRec etc) ?

likewise with other tests on windows

**Comment by citycide** [comment]
@timotheecour took me a bit to remember how I wrote the tests :laughing:

This template is used as a string literal prefix and splits on `/`, then uses [`os.joinPath`](https://nim-lang.org/docs/os.html#joinPath%2Cvarargs%5Bstring%5D) to stitch the parts back up with the correct OS directory separator:

https://github.com/citycide/glob/blob/e126bc92b53668fa41215407087b48e422c62b8a/tests.nim#L21-L22

**Comment by timotheecour** [comment]
ohhh i c....
