### ISSUE TITLE
glob doesn't like the "\" character

### ISSUE THREAD

**Issue by system64MC** [citycide/glob#57]
glob doesn't work properly when I use the "\" character for paths, but if I use the "/" character, it works fine. This bug may cause problems on Windows.

**Comment by system64MC** [comment]
For exemple if I do

`var args = commandLineParams() #contains the string to a path like "C:\myFolder\*.txt" passed by argument
var pattern = glob(args[0].string)`
for path in walkGlob(pattern):
    echo path`

it prints nothing but if I do

`var args = commandLineParams() #contains the string to a path like "C:/myFolder/*.txt" passed by argument, with a / instead of \
var pattern = glob(args[0].string)`
for path in walkGlob(pattern):
    echo path`
it will print the path to all txt files of the folder

**Comment by citycide** [comment]
This is the expected behavior in order to keep glob's syntax consistent across platforms. See the [Syntax section](https://glob.bolingen.me/latest/glob.html#syntax) of the docs. Snip:


> token | example    | description
> :---- | :--------- | :------------------------------------------------------
> `/`   | `foo/*.js` | literal path separator (even on Windows)
> `\`   | `foo\*.js` | escape character (not path separator, even on Windows)
> 
> Any other characters are matched literally. Make special note of the difference between `/` and `\`. Even when on Windows platforms you should **not** use `\` as a path separator, since it is actually the escape character in glob syntax. Instead, always use `/` as the path separator. This module will then use the correct separator when the glob is created.

Hope that helps.

**Comment by citycide** [comment]
Closing as this is documented behavior.
