### ISSUE TITLE
BUG: doesn't work if pattern has absolute path

### ISSUE THREAD

**Issue by timotheecour** [citycide/glob#6]
```nim
from glob import nil
for path in glob.walkGlob("/some_absolute_path/**/*): echo path
```
shows no path

**Comment by citycide** [comment]
Interesting, thanks for reporting. I'll look into it.

**Comment by citycide** [comment]
@timotheecour latest release [`v0.7.0`](https://github.com/citycide/glob/releases/tag/v0.7.0) should take care of this for you
