### ISSUE TITLE
`includeHidden=false` doesn't prevent recursion into hidden directories

### ISSUE THREAD

**Issue by timotheecour** [citycide/glob#7]
git clone https://github.com/AndreiRegiani/INim
cd INim

nim c -o:app -r /tmp/t31_glob.nim

/tmp/t31_glob.nim:
```nim
import glob
import strutils
let m = listGlob(".", includeHidden=false)
echo m.join("\n")
```

prints lines such as:
```
./src/nimcache/stdlib_linenoise.c
./.git/config
./.git/HEAD
```

which should've been filtered out by `includeHidden=false`

perhaps you're only filtering out hidden files, not hidden folders?

**Comment by citycide** [comment]
You're right, the source is here: https://github.com/citycide/glob/blob/ca0513dca6896972bf5277b4ec94202f51ba49a9/src/glob.nim#L314

The folder itself isn't yielded but when recursing there isn't another check before adding that directory to the stack. Should be a simple fix (~`isRec and (includeHidden or not path.isHidden) `) if you'd like to try a PR.

**Comment by timotheecour** [comment]
unfortunately my local fix hit that bug: https://github.com/nim-lang/Nim/issues/8225

**Comment by citycide** [comment]
Thanks for the update. This is really the only untested thing right now as I wasn't sure how to go about testing for hidden files. Should get some tests in there once we get this figured out.

**Comment by citycide** [comment]
Fix is pushed on our end, just need that Nim issue to be resolved.

**Comment by citycide** [comment]
Closing since we've fixed this in `glob`. If anyone still has this issue, update Nim itself to a version that includes the mentioned PR.

**Comment by timotheecour** [comment]
https://github.com/nim-lang/Nim/pull/8315 was finally merged, fixing this for good :)
